# Generated by Django 5.1.4 on 2024-12-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('expected_graduation', models.DateField()),
                ('relevant_subjects', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='Bucharest, Romania', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='Bucharest, Romania', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
